name: Build and Release

permissions:
  contents: write

on:
  push:
    branches: [main]

  # need this so I can trigger builds manually via website
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install vmnet-helper requirements
        run: brew install meson ninja

      - name: Build release binary
        run: cargo build --release

      - name: Set short git commit SHA
        id: vars
        run: |
          echo "SHA_SHORT=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date +'%Y-%m-%d')"                       >> $GITHUB_ENV

      - name: Package binary
        run: |
          cd target/release
          zip vibe-macos-arm64.zip vibe

      - name: Create sha release
        if: github.ref == 'refs/heads/main'
        run: |
          gh release create "${{ env.BUILD_DATE }}-${{ env.SHA_SHORT }}" \
            --title "${{ env.BUILD_DATE }}-${{ env.SHA_SHORT }}" \
            --notes "Built from commit ${{ github.sha }}" \
            target/release/vibe-macos-arm64.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete existing latest release
        if: github.ref == 'refs/heads/main'
        run: gh release delete latest --cleanup-tag --yes || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create latest release
        if: github.ref == 'refs/heads/main'
        run: |
          gh release create latest \
            --title "Latest" \
            --notes "Built from commit ${{ github.sha }}" \
            --prerelease \
            target/release/vibe-macos-arm64.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
